import { useState } from 'react';
import { X, AlertTriangle } from 'lucide-react';

interface SettingsModalProps {
  isOpen: boolean;
  onClose: () => void;
  langMode: string;
  setLangMode: (mode: string) => void;
  mode: string;
  setMode: (mode: string) => void;
}

export default function SettingsModal({ isOpen, onClose, langMode, setLangMode, mode, setMode }: SettingsModalProps) {
  const [showWarning, setShowWarning] = useState(false);

  if (!isOpen) return null;

  const handleModeChange = (newMode: string) => {
    if (newMode === 'real') {
      setShowWarning(true);
    } else {
      setMode(newMode);
    }
  };

  const confirmRealMode = () => {
    setMode('real');
    setShowWarning(false);
  };

  return (
    <div className="absolute inset-0 z-50 bg-black/90 backdrop-blur-md flex items-center justify-center p-6">
        <div className="glass-panel w-full max-w-sm rounded-xl p-6 relative">
            <button onClick={onClose} className="absolute top-4 right-4 text-gray-400 hover:text-white cursor-pointer">
                <X className="w-5 h-5" />
            </button>
            
            <h3 className="text-xl font-mono text-neon-blue mb-6 border-b border-gray-700 pb-2">SETTINGS</h3>
            
            {showWarning ? (
                <div className="space-y-4 animate-in fade-in zoom-in duration-200">
                    <div className="flex flex-col items-center text-center gap-3 p-4 bg-red-500/10 border border-red-500/30 rounded-lg">
                        <AlertTriangle className="w-10 h-10 text-red-500" />
                        <h4 className="text-red-500 font-bold text-lg">WARNING: REAL MODE</h4>
                        <p className="text-sm text-gray-300">
                            You are entering an <strong>uncensored, hard mode</strong>. 
                            The content generated by AI is not real and may contain <strong>offensive, vulgar, and abusive language</strong>.
                        </p>
                        <p className="text-xs text-gray-500 italic">
                            This is a fun AI app. Do not take it personally. Please do not proceed if you find such language offensive.
                        </p>
                    </div>
                    <div className="flex gap-3 pt-2">
                        <button 
                            onClick={() => setShowWarning(false)}
                            className="flex-1 py-2 bg-gray-800 hover:bg-gray-700 border border-gray-600 rounded text-sm text-white font-mono transition-colors"
                        >
                            CANCEL
                        </button>
                        <button 
                            onClick={confirmRealMode}
                            className="flex-1 py-2 bg-red-600 hover:bg-red-700 border border-red-500 rounded text-sm text-white font-bold font-mono transition-colors"
                        >
                            I UNDERSTAND
                        </button>
                    </div>
                </div>
            ) : (
                <div className="space-y-6">
                    {/* Language Mode */}
                    <div>
                        <label className="block text-xs text-gray-400 mb-2 uppercase tracking-wider">Bot Language Mode</label>
                        <select 
                            value={langMode}
                            onChange={(e) => setLangMode(e.target.value)}
                            className="w-full bg-black border border-gray-700 rounded p-2 text-sm text-white font-mono focus:border-neon-blue focus:outline-none"
                        >
                            <option value="malayalam">Pure Malayalam</option>
                            <option value="manglish">Manglish (Lazy Mode)</option>
                        </select>
                    </div>

                    {/* Thankan Mode */}
                    <div>
                        <label className="block text-xs text-gray-400 mb-2 uppercase tracking-wider">Thankan Mode</label>
                        <div className="flex gap-2">
                            <button 
                                onClick={() => handleModeChange('unreal')}
                                className={`flex-1 py-2 rounded text-sm font-mono border transition-all ${
                                    mode === 'unreal' 
                                    ? 'bg-neon-blue/20 border-neon-blue text-neon-blue' 
                                    : 'bg-gray-900 border-gray-800 text-gray-500 hover:border-gray-600'
                                }`}
                            >
                                UNREAL
                            </button>
                            <button 
                                onClick={() => handleModeChange('real')}
                                className={`flex-1 py-2 rounded text-sm font-mono border transition-all ${
                                    mode === 'real' 
                                    ? 'bg-red-500/20 border-red-500 text-red-500' 
                                    : 'bg-gray-900 border-gray-800 text-gray-500 hover:border-gray-600'
                                }`}
                            >
                                REAL
                            </button>
                        </div>
                        <p className="text-[10px] text-gray-500 mt-2">
                            {mode === 'unreal' ? 'Suspicious but clean language.' : 'Uncensored. 18+ Vulgarity. Use at own risk.'}
                        </p>
                    </div>

                    <div className="pt-4">
                        <button onClick={onClose} className="w-full py-2 bg-gray-800 hover:bg-gray-700 border border-gray-600 rounded text-sm text-white font-mono transition-colors cursor-pointer">
                            SAVE CHANGES
                        </button>
                    </div>
                </div>
            )}
        </div>
    </div>
  );
}
